name: SB IMMO FRONTEND CI-CD

on:
  push:
    paths:
      - "sb-immo-frontend/**"
  pull_request:
    paths:
      - "sb-immo-frontend/**"

jobs:
  angular-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sb-immo-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run tests
        run: npm test-in-github
